import { SignInButton, useUser } from "@clerk/nextjs";
import { type NextPage } from "next";
import Head from "next/head";
import { api } from '~/utils/api';

const CreatePostWizard = () => {
  const { user } = useUser();

  if (!user) return null;
  // console.log(user.id);
  return (
    <div className="flex gap-4 w-full">
      <img src={user.profileImageUrl} alt="profile image" className="w-14 h-14 rounded-full" />
      <input placeholder="type some emojis" className="bg-transparent grow" />
    </div>
  )
}

const Home: NextPage = () => {
  const user = useUser();
  const { data, isLoading } = api.posts.getAll.useQuery();

  if (isLoading) return <p>Loading...</p>;
  if (!data) return <p>Something went wrong!</p>;

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex justify-center h-full h-screen">
        <div className="h-full w-full border-x border-slate-400 md:max-w-2xl">
          <h1 className="text-xl ml-2 mb-5 font-bold">Chirp Chirp</h1>
          <div className="border-b border-slate-400 p-4">
            {user.isSignedIn ?
              <CreatePostWizard />
              : <SignInButton />}
          </div>
          <div className="flex flex-col">
            {data?.map(({ post }) => (
              <p key={post.id} className="p-8 border-b border-slate-400"> {post.content} </p>
            ))}
          </div>
        </div>

      </main>
    </>
  );
};

export default Home;
