import { SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import { type NextPage } from "next";
import Head from "next/head";
import { api } from '~/utils/api';

const CreatePostWizard = () => {
  const { user } = useUser();
  if (!user) return null;
  return (
    <div className="flex gap-4 w-full">
      <img src={user.profileImageUrl} alt="profile image" className="w-14 h-14 rounded-full" />
      <input placeholder="type some emojis" className="bg-transparent" />
    </div>
  )
}

const Home: NextPage = () => {
  const user = useUser();
  const { data, isLoading } = api.posts.getAll.useQuery();

  if (isLoading) return <p>Loading...</p>;
  if (!data) return <p>Something went wrong!</p>;

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {user.isSignedIn ?
          <CreatePostWizard />
          : <SignInButton />}
        <div className="flex flex-col">
          {data?.map(post => (
            <p key={post.id} className="p-8 border-b border-slate-400"> {post.content} </p>
          ))}
        </div>
      </main>
    </>
  );
};

export default Home;
